type Instance = any
type Part = any
type Model = any
type Vector3 = any
type CFrame = any
type RBXScriptSignal = any
type Color3 = any
type UDim2 = any
type RaycastParams = any

declare global game: any
declare global workspace: any
declare global script: Instance
declare global Enum: any
declare global task: any
declare global wait: (...any) -> ()
declare global Vector3: any
declare global CFrame: any
declare global Instance: any
declare global RaycastParams: any
